trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  displayName: 'Build and Push Docker image'
  inputs:
    containerRegistry: 'DockerHubServiceConnection' # Replace with your Docker Hub service connection name
    repository: 'softwaresimms/devops-project' # Replace with your repository on Docker Hub
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      latest
      $(Build.BuildId)

- task: Kubernetes@1
  displayName: 'Deploy to Kubernetes cluster'
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'AKS-Service-Connection' # Replace with your AKS service connection name
    azureResourceGroup: 'myResourceGroup' # Replace with your AKS resource group name
    kubernetesCluster: 'myAKSCluster' # Replace with your AKS cluster name
    command: 'apply'
    useConfigurationFile: true
    configuration: 'path/to/deployment.yaml' # Replace with the path to your deployment manifest in your repo
