trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  displayName: 'Build and Push Docker image'
  inputs:
    containerRegistry: 'Docker Hub' 
    repository: 'softwaresimms/devops-project' 
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      latest
      $(Build.BuildId)

- task: Kubernetes@1
  displayName: 'Deploy to Kubernetes cluster'
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'AKS' # Replace with your AKS service connection name
    azureResourceGroup: 'networking-resource-group' # Replace with your AKS resource group name
    kubernetesCluster: 'terraform-aks-cluster' # Replace with your AKS cluster name
    command: 'apply'
    useConfigurationFile: true
    configuration: 'path/to/application-manifest.yaml'
